spring.application.name=oneday_prj

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@211.63.89.137:1521/orcl
spring.datasource.username=oneday
spring.datasource.password=tiger


mybatis.config-location=classpath:mybatis-config.xml
mybatis.mapper-locations=classpath:mapper/*.xml